#!/usr/bin/env python3
"""Materialize the exact submitted paper artifacts from frozen reference results."""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "reference"
MARKER = ".generated_by_reproduce_paper"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_row(path: Path, key: str, value: str) -> dict[str, str]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        if row.get(key) == value:
            return row
    raise KeyError(f"No row with {key}={value!r} in {path}")


def reset_output(output: Path, force: bool) -> None:
    marker = output / MARKER
    if output.exists():
        if not force and not marker.exists():
            raise RuntimeError(
                f"Refusing to replace unmarked directory: {output}. "
                "Use --force only when that directory is disposable."
            )
        shutil.rmtree(output)
    output.mkdir(parents=True)
    (output / MARKER).write_text("Generated by scripts/reproduce_paper.py\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default="artifacts/paper")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    output = Path(args.output_dir)
    if not output.is_absolute():
        output = ROOT / output
    reset_output(output, force=args.force)

    for name in ("figures", "tables", "data"):
        shutil.copytree(REFERENCE / name, output / name)

    within = read_row(
        REFERENCE / "data/within_model/table1_within_model_summary.csv",
        "metric",
        "Harmora",
    )
    cross = read_row(
        REFERENCE / "data/cross_model/cross_model_selection_overall_summary.csv",
        "metric",
        "Harmora",
    )
    runtime = next(
        csv.DictReader(
            (REFERENCE / "data/runtime/real_overall_runtime_summary.csv").open(
                newline="", encoding="utf-8"
            )
        )
    )
    precision = read_row(
        REFERENCE / "data/precision/method_summary.csv",
        "method",
        "adaptive_precision",
    )

    summary = {
        "experiment": {"models": 7, "tasks": 11, "seeds": [11, 22, 33, 44]},
        "within_model": {
            "harmora_mean_spearman": float(within["mean_spearman"]),
            "rank": int(within["rank"]),
        },
        "cross_model": {
            "selected_percentile": float(cross["selected_percentile_mean"]),
            "ndcg_at_1": float(cross["ndcg_at_1_mean"]),
            "ndcg_at_3": float(cross["ndcg_at_3_mean"]),
            "top5_overlap": float(cross["top5_overlap_mean"]),
        },
        "runtime": {
            "exhaustive_seconds": float(runtime["exhaustive_evaluator_s"]),
            "hybrid_seconds": float(runtime["hybrid_total_s"]),
            "speedup": float(runtime["hybrid_speedup"]),
        },
        "adaptive_precision_at_25_percent": {
            "ndcg_at_5": float(precision["mean_ndcg_at_k"]),
            "utility_spearman": float(precision["mean_utility_spearman"]),
        },
    }
    (output / "RESULTS.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

    manifest: dict[str, str] = {}
    for path in sorted(output.rglob("*")):
        if path.is_file() and path.name not in {MARKER, "MANIFEST_SHA256.json"}:
            manifest[str(path.relative_to(output))] = sha256(path)
    (output / "MANIFEST_SHA256.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8"
    )

    print(f"Exact paper artifacts written to: {output}")
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
